name: classroom_navigator
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.2
  provider: ^6.1.2
  # Maps_flutter: ^2.6.1 # CORRECTED NAME
  geolocator: ^12.0.0
  flutter_typeahead: ^5.2.0
  intl: ^0.19.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  # geolocator: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png